spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: ${REDIS_HOST:loxalhost}
    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:}

#  redis:
#    database: 0
##    password: 12345678
#    port: 6379
#    timeout: 0
#    pool:
#      max-active: 8
#      max-idle: 8
#      max-wait: -1
#      min-idle: 0
#    sentinel:
#      master: master1
#      nodes: 172.16.14.163:6379,172.16.14.163:16379
server:
  port: 9091

#: ===============================

